import './globals.css'

import type { Metadata, Viewport } from 'next'
import localFont from 'next/font/local'

import { cn } from '@/lib/utils'
import { Providers } from '@/providers/providers'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900'
})
// const geistMono = localFont({
// 	src: './fonts/GeistMonoVF.woff',
// 	variable: '--font-geist-mono',
// 	weight: '100 900'
// })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export const viewport: Viewport = {
	themeColor: [
		{ media: '(prefers-color-scheme: light)', color: 'white' },
		{ media: '(prefers-color-scheme: dark)', color: 'black' }
	]
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang='en'
			suppressHydrationWarning>
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased',
					geistSans.variable
				)}>
				<Providers>
					<div vaul-drawer-wrapper=''>
						<div className='relative flex min-h-screen flex-col bg-background'>
							{children}
						</div>
					</div>
				</Providers>
			</body>
		</html>
	)
}
